"""Compile a 2-input fuzzy system into a lookup table for embedded targets.

Running a full Mamdani inference on a PLC scan cycle or an 8-bit MCU is
wasteful; the standard industrial practice is to pre-compute the control
surface offline and interpolate it at run time.  This module emits

* a C header (Arduino / ESP32 / STM32 / micro-ROS firmware), and
* an IEC 61131-3 Structured Text function block (Siemens TIA, CODESYS, Beckhoff,
  Schneider ...) implementing the complete incremental fuzzy-PI controller.
"""
from __future__ import annotations

from typing import Callable, Tuple

import numpy as np


def build_lut(fn: Callable[[float, float], float], x_range: Tuple[float, float],
              y_range: Tuple[float, float], nx: int = 21, ny: int = 21):
    """Sample fn(x, y) on an nx-by-ny grid; returns (xs, ys, table[iy, ix])."""
    xs = np.linspace(*x_range, nx)
    ys = np.linspace(*y_range, ny)
    table = np.array([[fn(x, y) for x in xs] for y in ys])  # table[iy, ix]
    return xs, ys, table


def interp_lut(xs, ys, table, x, y) -> float:
    """Bilinear interpolation with clamping; mirrors the generated C / ST code."""
    x = min(max(x, xs[0]), xs[-1])
    y = min(max(y, ys[0]), ys[-1])
    ix = min(int((x - xs[0]) / (xs[1] - xs[0])), len(xs) - 2)
    iy = min(int((y - ys[0]) / (ys[1] - ys[0])), len(ys) - 2)
    fx = (x - xs[ix]) / (xs[1] - xs[0])
    fy = (y - ys[iy]) / (ys[1] - ys[0])
    t = table
    return float((1 - fx) * (1 - fy) * t[iy, ix] + fx * (1 - fy) * t[iy, ix + 1]
                 + (1 - fx) * fy * t[iy + 1, ix] + fx * fy * t[iy + 1, ix + 1])


def to_c_header(xs, ys, table, name: str = "fuzzy_lut") -> str:
    """C99 header with the table and a bilinear-interpolation function."""
    rows = ",\n".join("    {" + ", ".join(f"{v:.5f}f" for v in row) + "}" for row in table)
    up = name.upper()
    return f"""/* Auto-generated by agriclimate.fuzzy.codegen - do not edit by hand. */
#ifndef {up}_H
#define {up}_H

#define {up}_NX {len(xs)}
#define {up}_NY {len(ys)}
static const float {name}_x0 = {xs[0]:.5f}f, {name}_dx = {xs[1] - xs[0]:.6f}f;
static const float {name}_y0 = {ys[0]:.5f}f, {name}_dy = {ys[1] - ys[0]:.6f}f;
static const float {name}_table[{up}_NY][{up}_NX] = {{
{rows}
}};

static inline float {name}_clampf(float v, float lo, float hi) {{ return v < lo ? lo : (v > hi ? hi : v); }}

/* Bilinear interpolation of the control surface (x = error, y = error rate). */
static inline float {name}_eval(float x, float y) {{
    float fxi, fyi, fx, fy; int ix, iy;
    x = {name}_clampf(x, {name}_x0, {name}_x0 + {name}_dx * ({up}_NX - 1));
    y = {name}_clampf(y, {name}_y0, {name}_y0 + {name}_dy * ({up}_NY - 1));
    fxi = (x - {name}_x0) / {name}_dx; fyi = (y - {name}_y0) / {name}_dy;
    ix = (int)fxi; iy = (int)fyi;
    if (ix > {up}_NX - 2) ix = {up}_NX - 2;
    if (iy > {up}_NY - 2) iy = {up}_NY - 2;
    fx = fxi - ix; fy = fyi - iy;
    return (1 - fx) * (1 - fy) * {name}_table[iy][ix] + fx * (1 - fy) * {name}_table[iy][ix + 1]
         + (1 - fx) * fy * {name}_table[iy + 1][ix] + fx * fy * {name}_table[iy + 1][ix + 1];
}}

#endif /* {up}_H */
"""


def to_iec_st(xs, ys, table, name: str = "FB_FuzzyPIClimate") -> str:
    """IEC 61131-3 function block with the table and the complete incremental fuzzy-PI."""
    nx, ny = len(xs), len(ys)
    flat = ", ".join(f"{v:.4f}" for v in table.flatten())
    return f"""(* Auto-generated by agriclimate.fuzzy.codegen - IEC 61131-3 Structured Text *)
(* Incremental fuzzy-PI climate controller. Call cyclically every tCycle.       *)
(* rDemand > 0 : heating demand, rDemand < 0 : cooling demand (-1 .. 1).        *)
FUNCTION_BLOCK {name}
VAR_INPUT
    rSetpoint   : REAL;          (* degC *)
    rMeasured   : REAL;          (* degC, validated sensor value *)
    rKe         : REAL := 0.3;   (* 1/degC  : error scaling *)
    rKr         : REAL := 200.0; (* s/degC  : error-rate scaling *)
    rKu         : REAL := 0.0015; (* 1/s     : output increment scaling *)
    rFilter     : REAL := 30.0;  (* s       : error-rate low-pass filter *)
    tCycle      : TIME := T#1S;
    xEnable     : BOOL;
    xTrack      : BOOL;          (* bumpless transfer: follow rTrackValue *)
    rTrackValue : REAL;
END_VAR
VAR_OUTPUT
    rDemand     : REAL;
END_VAR
VAR
    aLut   : ARRAY[0..{nx * ny - 1}] OF REAL := [{flat}];
    rErrPrev, rRateF, rE, rDe, rDu, rDt, fx, fy, rX, rY : REAL;
    ix, iy : INT;
    xInit  : BOOL;
END_VAR
VAR CONSTANT
    NX : INT := {nx}; NY : INT := {ny};
    X0 : REAL := {xs[0]:.4f}; DX : REAL := {xs[1] - xs[0]:.6f};
    Y0 : REAL := {ys[0]:.4f}; DY : REAL := {ys[1] - ys[0]:.6f};
END_VAR

rDt := TIME_TO_REAL(tCycle) / 1000.0;
IF NOT xEnable THEN
    rDemand := 0.0; xInit := FALSE; RETURN;
END_IF
IF NOT xInit THEN
    rErrPrev := rSetpoint - rMeasured; rRateF := 0.0; xInit := TRUE;
END_IF
IF xTrack THEN
    rDemand := rTrackValue; rErrPrev := rSetpoint - rMeasured; RETURN;
END_IF

rE  := LIMIT(-1.0, (rSetpoint - rMeasured) * rKe, 1.0);
rRateF := rRateF + rDt / (rFilter + rDt) * (((rSetpoint - rMeasured) - rErrPrev) / rDt - rRateF);
rDe := LIMIT(-1.0, rRateF * rKr, 1.0);
rErrPrev := rSetpoint - rMeasured;

rX := (rE - X0) / DX;  rY := (rDe - Y0) / DY;
ix := MIN(REAL_TO_INT(TRUNC(rX)), NX - 2);  iy := MIN(REAL_TO_INT(TRUNC(rY)), NY - 2);
fx := rX - INT_TO_REAL(ix);  fy := rY - INT_TO_REAL(iy);
rDu := (1.0 - fx) * (1.0 - fy) * aLut[iy * NX + ix] + fx * (1.0 - fy) * aLut[iy * NX + ix + 1]
     + (1.0 - fx) * fy * aLut[(iy + 1) * NX + ix] + fx * fy * aLut[(iy + 1) * NX + ix + 1];

(* integrate with clamping anti-windup *)
rDemand := LIMIT(-1.0, rDemand + rKu * rDu * rDt, 1.0);
END_FUNCTION_BLOCK
"""
